Repository phovea/phovea_ui, pull requests merged in 2020-01, with the labels that each got.

#85 Remove .travis.yml and .gitlab-ci.yml
  .gitlab-ci.yml
  .travis.yml
Labels: release: major, type: technical debt

#83 Specify Node.js minor version + Debian Buster in CI configs
  .circleci/config.yml
Labels: release: patch, type: refactor

#87 Release 3.1.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  package-lock.json
  package.json
Labels: release: minor
