Repository phovea/phovea_ui, pull requests merged in 2021-03, with the labels that each got.

#141 Fix SASS `$theme-color` assignment
  dist/scss/abstracts/_variables.scss
  src/scss/abstracts/_variables.scss
Labels: release: minor, type: refactor

#140 Make the styles of dark theme of the phovea header more specific
  dist/components/header.js
  dist/scss/abstracts/_variables.scss
  dist/scss/components/_header_navbar.scss
  src/components/header.ts
  src/scss/abstracts/_variables.scss
  src/scss/components/_header_navbar.scss
Labels: release: patch, type: bug

#144 Add `positionFixed` option to header
  dist/components/header.d.ts
  dist/components/header.js
  dist/components/header.js.map
  src/components/header.ts
Labels: release: minor, type: feature
